---
# tasks file for mongodb
- include_vars: secrets.yml 
- name: Install mongodb
  apt:  
    name: mongodb
    state: present
- name: start and enable the engine
  service: 
    name: mongodb
    state: started
    enabled: yes
- name: allow for outside connections
  lineinfile: 
    path: /etc/mongodb.conf
    regexp: '^#?bind_ip = 127.0.0.1'
    line: '#bind_ip = 127.0.0.1'
  notify: 
    - restart mongodb
- name: Install Pip 
  apt: 
    name: python-pip 
    state: present 
- name: Install Pymongo 
  pip: 
    name: pymongo 
    state: present
- name: check if the admin user is already created
  command: grep "^auth = true" /etc/mongodb.conf
  register: auth
  ignore_errors: yes
- name: Add an admin to db
  mongodb_user:
    database: admin
    name: root 
    password: "{{ dbpass }}"
    roles: root
    state: present
  when: auth.rc == 1   #false
- name: enable auth 
  lineinfile: 
    path: /etc/mongodb.conf
    regexp: '#?auth \= true'
    line: 'auth = true'
  notify: restart mongodb 
- name: create the app user
  mongodb_user: 
    login_user: root 
    login_password: "{{ dbpass }}"
    name: "{{ appdbuser }}"
    password: "{{ appdbpass }}"
    database: "{{ dbname }}"
    roles: dbOwner 
    state: present
  name: stop firewall to allow outside connections 
  service: 
    name: ufw
    state: stopped 
     